export const FIRST_NAME = 'USER_FIRST_NAME';
export const LAST_NAME = 'USER_LAST_NAME';
export const EMAIL = 'USER_EMAIL';
export const STATE_CODE = 'USER_STATE_CODE';
export const MOBILE = 'USER_MOBILE';
export const HAS_STATE_LICENSE = 'HAS_STATE_LICENSE';

export const SCHOOL_INVITE_NAME = 'SCHOOL_INVITE_NAME';
export const SCHOOL_INVITE_STATE_CODE = 'SCHOOL_INVITE_STATE_CODE';
export const SCHOOL_INVITE_CITY = 'SCHOOL_INVITE_CITY';
export const SCHOOL_INVITE_ZIPCODE = 'SCHOOL_INVITE_ZIPCODE';

export const AUTH_EMAIL = 'AUTH_EMAIL';
export const AUTH_PASSWORD = 'AUTH_PASSWORD';
export const AUTH_RESET_PASSWORD = 'AUTH_RESET_PASSWORD';
export const AUTH_RESET_CONFIRM_PASSWORD = 'AUTH_RESET_CONFIRM_PASSWORD';

export const REMINDER_SHOW_CONFIG = 'REMINDER_SHOW_CONFIG';
export const REMINDER_USE_SMS = 'REMINDER_USE_SMS';

export const userMap = {
  firstName: FIRST_NAME,
  lastName: LAST_NAME,
  email: EMAIL,
  stateCode: STATE_CODE,
  mobile: MOBILE,
  hasStateLicense: HAS_STATE_LICENSE,
};
