export const CREATE_USER_STEP = 'CREATE_USER_STEP';

export const FIND_SCHOOL_STEP = 'FIND_SCHOOL_STEP';

export const INVITE_SCHOOL_STEP = 'INVITE_SCHOOL_STEP';

export const REGISTRATION_STATUS_STEP = 'REGISTRATION_STATUS_STEP';

export const RULES_STEP = 'RULES_STEP';

export const OVR_STEP = 'OVR_STEP';

export const FORM_STEP = 'FORM_STEP';

export const MAIL_FORM_STEP = 'MAIL_STEP';

export const STILL_IMPACT_STEP = 'STILL_IMPACT_STEP';

export const CUSTOM_MESSAGE_STEP = 'CUSTOM_MESSAGE_STEP';

export const THANKS_STEP = 'THANKS_STEP';
